##############################
# Explicit WiFi configuration
##############################
[wifi]
ssid=XXXX
password=XXXX

##############################
# openweathermap
##############################
[own]
api_key=XXXX

##############################
# Location information
##############################
[location]
name=XXXX
lat=XXXX
lon=XXXX
